import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header, Footer } from "../components/root";

const inter = Inter({ subsets: ["latin"] });

interface ILayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Ansh Shukla",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ILayoutProps) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#23ACEC]`}>
        <div className="flex flex-col min-h-screen bg-transparent">
          <Header />
          <main className="grow flex flex-col justify-center bg-background dark:bg-background-dark">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
